### ISSUE TITLE
Incorrect Polls 

### ISSUE THREAD

**Issue by joseaveldanes** [dlab-berkeley/Python-Fundamentals#25]
The polls that are in the Python Fundamentals Pilot are for the R fundamentals.

**Comment by aculich** [comment]
@tomvannuenen @heroashman let's debrief the poll creation to figure out how these got mixed up.
The way Zoom currently does poll management manually is a bit onerous and I expect I know how it went wrong because their setup is so confusing (at least to me).

I also have a partial solution that I am working to implement before we provision the summer workshops, so let's chat more about this.

@joseaveldanes thanks for reporting this!
